package:
  name: estuarial 
  version: 0.0.1

source:
  git_url: git@github.com:ContinuumIO/estuarial.git

requirements:
  build:
    - python

  run:
    - python
    - arraymanagement >=0.1
    - pyodbc >=3.0.7
    - pytables
    - pandas
    - yaml
    - pyyaml
    - sqlalchemy >=0.9.1

about: 
   home: https://github.com/ContinuumIO/estuarial
   license: BSD
